{{ config(materialized='table') }}

SELECT
    sales_report_id AS sale_id,
    transaction_item_id,
    transaction_id,
    paypal_transaction_id,
    catalog_number,
    item_type,
    item_name,
    artist,
    package,
    item_url,
    currency,
    item_price,
    quantity,
    sub_total,
    shipping,
    transaction_fee,
    item_total,
    amount_you_received,
    net_amount,
    additional_fan_contribution,
    sale_date,
    ship_date,
    buyer_name,
    buyer_email,
    buyer_note,
    ship_to_name,
    ship_to_street,
    ship_to_city,
    ship_to_state,
    ship_to_zip,
    ship_to_country,
    ship_notes,
    referer,
    referer_url
FROM {{ ref('stg_bandcamp_sales_report') }}
WHERE item_type NOT IN ('refund', 'payout')